version: '3'

vars:
  ORG: dattached
  LOCAL_DIR: '{{.ROOT_DIR}}/.local'
  # versions
  BOOTSTRAP_VERSION: {sh: sed -ne 's/ARG VERSION=\(.*\)/\1/p' bootstrap/Dockerfile}
  LAZYDOCKER_VERSION: {sh: sed -ne 's/ARG LAZYDOCKER_VERSION=\(.*\)/\1/p' lazydocker/Dockerfile}
  USQL_VERSION: {sh: sed -ne 's/ARG USQL_VERSION=\(.*\)/\1/p' usql/Dockerfile}
  VERSIONS:
    ref: dict
      "bootstrap" .BOOTSTRAP_VERSION
      "lazydocker" .LAZYDOCKER_VERSION
      "usql" .USQL_VERSION

env:
  DOCKER_CONFIG: '{{.LOCAL_DIR}}/docker'

tasks:

  # init

  init:
    desc: Initialize dev environment.
    cmds:
      - task: init:homebrew

  init:homebrew:
    internal: true
    dir: .dev
    sources: [.dev/Brewfile]
    env:
      HOMEBREW_BUNDLE_NO_LOCK: 1
    cmds:
      - brew bundle

  # docker

  login:
    internal: true
    status:
      - test -d ${DOCKER_CONFIG}
    cmds:
      - mkdir -p ${DOCKER_CONFIG}
      - docker -c default login -u {{.ORG}}

  logout:
    internal: true
    cmds:
      - docker logout

  # build

  build:*:
    desc: Build dattached/* image.
    vars:
      IMG: '{{index .MATCH 0}}'
    deps: [login]
    dir: '{{.IMG}}'
    run: once
    cmds:
      - task -t Taskfile.update.yml update
      - docker buildx bake

  # test run

  testrun:*:
    desc: Test and/or run newly built dattached/* image.
    vars:
      IMG: '{{index .MATCH 0}}'
    cmds:
      - task: testrun-bake:{{.IMG}}
      - task: testrun-compose:{{.IMG}}

  testrun-bake:*:
    internal: true
    vars:
      IMG: '{{index .MATCH 0}}'
    env:
      BUILDKIT_PROGRESS: plain
    dir: '{{.IMG}}'
    status:
      - '! hcl2json docker-bake.hcl | jq -e ".group.test"'
    cmds:
      - task: build:{{.IMG}}
      - docker buildx bake test

  testrun-compose:*:
    internal: true
    vars:
      IMG: '{{index .MATCH 0}}'
    env:
      COMPOSE_FILE: '{{.IMG}}/tests/compose.yml'
    status:
      - '! test -f ${COMPOSE_FILE}'
    cmds:
      - task: build:{{.IMG}}
      - docker compose down  # handle previous failures
      - docker compose up {{.IMG}} --detach
      - docker compose attach {{.IMG}}
      - defer: docker compose down

  # release

  release:*:
    desc: Release newly built dattached/* image.
    vars:
      IMG: '{{index .MATCH 0}}'
      VERSION:
        sh: hcl2json {{.IMG}}/docker-bake.hcl | jq -r '.variable.version[].default'
    dir: '{{.IMG}}'
    status:
      - 'docker pull dattached/{{.IMG}}:{{.VERSION}}'
    cmds:
      - git tag -a "{{.IMG}}-{{.VERSION}}" -m "release dattached/{{.IMG}}:{{.VERSION}}"
      - docker buildx bake release

  # clean

  clean:
    desc: Cleanup local files.
    cmds:
      - task: logout
      - rm -rf {{.LOCAL_DIR}}
